### ISSUE TITLE
USB productid changed after flashing

### ISSUE THREAD

**Issue by g-ollivier** [adafruit/atmel-samd-micropython-vagrant#2]
Hello,
After flashing a feather m0 proto, I noticed that the USB references changed (productid field).
So I could not flash it again.

In order to be able to flash again the board, I would suggest to add 2 lines in the Vagrantfile
    vb.customize ["usbfilter", "add", "0", "--target", :id, "--name", "Adafruit Feather M0", "--vendorid", "0x239a", "--productid", "0x000b"]
    vb.customize ["usbfilter", "add", "1", "--target", :id, "--name", "MicroPython M0", "--vendorid", "0x239a", "--productid", "0x800b"]
The first line helps to see the board when it was used as an arduino.
The second line helps to see the board and flash is again as a MicroPython board.

**Comment by g-ollivier** [comment]
Correction : the productid field changes when setting the board ready for flashing (double reset) and returns to the original productid after

**Comment by tdicola** [comment]
Yep this was a small issue with the SAMD21 MicroPython firmware a few weeks ago.  It should be resolved as of a build from ~a week ago.  Will close this issue for now, thanks!
