### ISSUE TITLE
using same environment for esp8266

### ISSUE THREAD

**Issue by g-ollivier** [adafruit/atmel-samd-micropython-vagrant#3]
Hello,
As the esp8266 build is often used to test new features, it may be easier to add a line in the vagrant file in order to access an an adafruit esp8266 board (huzzah or feather).
So I added in the Vagrantfile
vb.customize ["usbfilter" , "add", "2", "--target", :id, "--name", "Feather esp8266", "--vendorid", "0x10C4", "--productid", "0xea60"]
Can you confirm vendorid and productid are correct ?
Thanks

**Comment by kattni** [comment]
This library is no longer being supported. Please consider this guide on building CircuitPython for future reference: https://learn.adafruit.com/building-circuitpython
